"""P5's exit test: the whole stack over a scripted Cold Plains.

Everything real except the game — the engine, the ladder with the shipped
`config/necro.toml` numbers, the necro module, the steps, the pickit, the
executor's verified-switch path, and `SafetyMonitor`. The world reacts the
way the client would and, crucially, is allowed to refuse.

The assertions below are the go/no-go artifact in test form; the readable
version is generated by `python -m tests.simworld`.
"""

import pytest

from pd2bot import offsets
from pd2bot.behavior.actions import (
    AttackUnit,
    CastAtPoint,
    CastSelf,
    DrinkPotion,
    PickUpItem,
)
from pd2bot.behavior.engine import IdleBail
from pd2bot.behavior.necro import CombatConfig
from pd2bot.safety import ChickenExit
from tests.simworld import (
    ARRIVAL,
    HEAL_KIND,
    ColdPlains,
    SimMonster,
    build_sim,
    cold_plains_scenario,
    patrol_scenario,
)

MAX_TICKS = 400


def run_to_completion(sim, world, *, max_ticks=MAX_TICKS):
    for _ in range(max_ticks):
        if sim.engine.tick():
            return True
        world.advance_tick(0.5)
    return False


@pytest.fixture
def sim(monkeypatch):
    world = cold_plains_scenario()
    return build_sim(world, monkeypatch=monkeypatch), world


# -- the patrol (2026-08-01) ----------------------------------------------------


@pytest.fixture
def patrol_sim(monkeypatch):
    world = patrol_scenario()
    return (
        build_sim(
            world, monkeypatch=monkeypatch, run_file="cold-plains-patrol.toml"
        ),
        world,
    )


def test_the_patrol_finds_a_pack_a_standstill_would_have_missed(patrol_sim):
    """The change's whole purpose, in one test.

    Both live runs on 2026-08-01 completed `[CVRL]` without a single
    `AttackUnit`, because nothing happened to be near the arrival point.
    Here the monsters are ~70 subtiles out — inside the patrol circle,
    outside anything a standing character reaches.
    """
    run, world = patrol_sim
    assert run_to_completion(run, world), "the run never finished"
    assert not world.monsters, "the pack survived the clearance"
    assert any(
        isinstance(entry.action, AttackUnit) for entry in run.trace
    ), "it never actually fought"


def test_the_patrol_actually_walked(patrol_sim):
    # A scenario that passes without walking would be the same blind spot
    # in a new costume.
    run, world = patrol_sim
    run_to_completion(run, world)
    moved = [e for e in run.trace if type(e.action).__name__ == "MoveTo"]
    assert len(moved) > 5, f"barely moved: {[e.action for e in moved]}"
    assert world.position != ARRIVAL


def test_the_patrol_reaches_its_points_rather_than_abandoning_them(patrol_sim):
    """The failure the first cut hid behind a green suite.

    `patrol_attempts` counted LEGS, and consecutive ring points are ~48
    subtiles apart, so three 12-subtile legs always fell one short: the
    sim abandoned seven of its eight points while every assertion
    passed. Counting legs that got no closer, instead of legs, fixed it.
    Assert the outcome, since that is what the green suite failed to.
    """
    run, world = patrol_sim
    run_to_completion(run, world)
    log = run.engine.report.log
    assert not [line for line in log if "giving up" in line], (
        "points were abandoned: "
        + "; ".join(line for line in log if "giving up" in line)
    )
    # Per STEP, not across the run. The clearance always walks its ring
    # (it could only ever see 46-67 subtiles of a 96-radius circle from a
    # standstill — T51). The sweep re-walks only on EVIDENCE since T3
    # (R186): either it had pending sightings and walked all 8, or its
    # memo was clean and it skipped the ring, saying so.
    reached = [
        line for line in log
        if "patrol reached" in line and "step clear_radius:" in line
    ]
    assert len(reached) == 8, f"clearance reached {len(reached)} of 8 points"
    swept = [
        line for line in log
        if "patrol reached" in line and "step pickup:" in line
    ]
    skipped = [line for line in log if "ring walk skipped" in line]
    assert len(swept) == 8 or skipped, (
        "the sweep neither walked its ring nor recorded why it skipped"
    )


# -- the full run ---------------------------------------------------------------


def test_the_whole_run_completes(sim):
    run, world = sim
    assert run_to_completion(run, world), "the run never finished"
    assert run.engine.report.steps_completed == [
        "town_preamble", "waypoint", "clear_radius", "pickup", "done",
    ]
    assert world.preamble_runs == 1
    assert world.travels == [offsets.AREA_COLD_PLAINS]


def test_the_narrative_is_o_actions_not_o_ticks(monkeypatch):
    """The coarseness contract (R179), measured: a full run's narrative is
    a story a human reads in one screen — lines scale with meaningful
    acts, never with ticks. If this ratio creeps up, some call site has
    started narrating inside a loop and belongs in the micro-log."""
    world = cold_plains_scenario()
    lines = []
    run = build_sim(world, monkeypatch=monkeypatch, narrate=lines.append)
    assert run_to_completion(run, world), "the run never finished"
    ticks = run.engine.report.ticks
    assert lines[0].startswith("run: ")
    assert lines[-1].startswith("run complete")
    assert len(lines) < max(15, ticks / 4), (
        f"{len(lines)} narrative lines over {ticks} ticks — the coarseness "
        "contract has been broken:\n" + "\n".join(lines)
    )


def test_no_cast_was_ever_sent_on_an_unverified_skill(sim):
    # The single most expensive mistake available to this bot: casting
    # whatever the game happens to have selected. The world counts them.
    run, world = sim
    run_to_completion(run, world)
    assert world.casts_on_unverified_skill == 0


def test_every_cast_was_preceded_by_its_hotkey(sim):
    run, world = sim
    run_to_completion(run, world)
    casts = [e for e in run.trace if isinstance(e.action, CastAtPoint | CastSelf)]
    assert casts, "the run cast nothing at all"
    assert all("verified" in e.detail for e in casts)


def test_attacks_stand_still_and_pickups_do_not(sim):
    run, world = sim
    run_to_completion(run, world)
    modifiers = {}
    for (_, button, stand_still) in run.gated.clicks:
        modifiers.setdefault(button, set()).add(stand_still)
    # Left-clicks come in two flavours and the difference is load-bearing:
    # an attack holds SHIFT, a pickup must not.
    attacks = [e for e in run.trace if isinstance(e.action, AttackUnit)]
    pickups = [e for e in run.trace if isinstance(e.action, PickUpItem)]
    assert attacks and pickups
    assert modifiers["left"] == {True, False}
    assert modifiers["right"] == {False}  # casts are never shifted


def test_the_pack_was_killed_and_the_radius_settled(sim):
    run, world = sim
    run_to_completion(run, world)
    assert world.monsters == []
    assert any("clear for" in line for line in run.engine.report.log)


def test_the_late_straggler_reset_the_settle_timer(sim):
    # A monster arriving mid-settle must not be walked away from.
    run, world = sim
    run_to_completion(run, world)
    assert any("struck 4" in line for line in world.log)


def test_poison_did_the_killing(sim):
    # No flurries: a struck monster is dying, and re-stabbing it inside
    # its restrike window is time not spent on the next one. A re-strike
    # AFTER the window is designed behavior (restrike_s exists for it,
    # and the M6 P3 revive-urgency hold shifts timing enough for an
    # adjacent survivor to legitimately earn one) — what must never
    # happen is two strikes on one monster within the window.
    run, world = sim
    run_to_completion(run, world)
    strikes = [
        (e.action.unit_id, e.at)
        for e in run.trace
        if isinstance(e.action, AttackUnit)
    ]
    struck = [uid for uid, _ in strikes]
    assert sorted(set(struck)) == [1, 2, 3, 4]
    window = CombatConfig().restrike_s
    last: dict[int, float] = {}
    for uid, at in strikes:
        if uid in last:
            assert at - last[uid] >= window, (
                f"monster {uid} re-struck {at - last[uid]:.2f}s after the "
                f"last strike (window {window})"
            )
        last[uid] = at
    assert sum("died of poison" in line for line in world.log) == 4


# -- the ladder ------------------------------------------------------------------


def test_the_damage_spike_triggered_the_escape(sim):
    run, world = sim
    run_to_completion(run, world)
    assert "blood_warp" in run.engine.report.reflex_fires
    assert any("blood warp" in line for line in world.log)


def test_the_escape_fired_exactly_once(sim):
    # Blood warp costs 12% of max hp, which on the next tick reads as more
    # incoming burst damage unless the ladder forgets its history — the bug
    # this sim found, where one escape cost two warps and 240 hp.
    run, world = sim
    run_to_completion(run, world)
    warps = [
        e for e in run.trace
        if isinstance(e.action, CastAtPoint)
        and e.action.skill_id == offsets.SKILL_BLOOD_WARP
    ]
    assert len(warps) == 1


def test_potions_were_drunk_and_armor_kept_up(sim):
    run, world = sim
    run_to_completion(run, world)
    assert any(isinstance(e.action, DrinkPotion) for e in run.trace)
    assert any(isinstance(e.action, CastSelf) for e in run.trace)
    assert world.armor_ratio == pytest.approx(1.0)


def test_the_ladder_outranks_offense(sim):
    # Every tick the ladder fired is a tick the run step did not act on.
    run, world = sim
    run_to_completion(run, world)
    fires = run.engine.report.reflex_fires
    assert fires
    assert len(fires) < run.engine.report.ticks


def test_the_revive_wall_was_raised_to_three(sim):
    run, world = sim
    run_to_completion(run, world)
    assert len(world.revives) == 3
    revive_casts = [
        e for e in run.trace
        if isinstance(e.action, CastAtPoint)
        and e.action.skill_id == offsets.SKILL_REVIVE
    ]
    assert len(revive_casts) == 3  # no wasted casts on already-raised corpses


def test_desecrate_was_bounded(sim):
    # It is cast to MAKE corpses; when it produces none the module must
    # stop rather than spend the run casting.
    run, world = sim
    run_to_completion(run, world)
    desecrates = sum(
        1 for e in run.trace
        if isinstance(e.action, CastAtPoint)
        and e.action.skill_id == offsets.SKILL_DESECRATE
    )
    assert 0 < desecrates <= 12


# -- pickit ----------------------------------------------------------------------


def test_the_pickit_decided_correctly(sim):
    run, world = sim
    run_to_completion(run, world)
    picked = {
        e.action.unit_id: e.action.position
        for e in run.trace if isinstance(e.action, PickUpItem)
    }
    # 501 healing potion -> belt; 503 rare -> keep; 504 unique -> attempted
    # and refused; 502 magic -> never touched, no rule matches it.
    assert 501 in picked and 503 in picked and 504 in picked
    assert 502 not in picked
    assert HEAL_KIND in [kind for kind, _ in world.belt]
    assert 999 in world.inventory


def test_the_stuck_item_was_bounded_and_flagged(sim):
    run, world = sim
    run_to_completion(run, world)
    attempts = [
        e for e in run.trace
        if isinstance(e.action, PickUpItem) and e.action.unit_id == 504
    ]
    # Two bounded rounds, not an endless loop: one full click schedule
    # before the cleanse, and — because the cleanse freed space — one
    # more after, sharing one memory across both pickup steps.
    services = run.engine._states[2].services
    assert len(attempts) == 2 * services.pickup_click_attempts
    # And the conclusion was recorded where the rest of the game can see it.
    assert services.inventory_full
    assert 504 in services.stuck


def test_the_run_still_finished_with_a_full_inventory(sim):
    # A full inventory costs loot; it must not stall the run.
    run, world = sim
    assert run_to_completion(run, world)


# -- the safety layer beneath everything -------------------------------------------


def test_the_monitor_chickens_through_the_engine(monkeypatch):
    world = cold_plains_scenario()
    run = build_sim(world, monkeypatch=monkeypatch)
    # Walk the run into the field, then drop below the 35% threshold.
    for _ in range(10):
        run.engine.tick()
        world.advance_tick(0.5)
    world.hp = 200  # 20% of max
    with pytest.raises(ChickenExit):
        for _ in range(5):
            run.engine.tick()
            world.advance_tick(0.5)


def test_a_stalled_run_idle_bails(monkeypatch):
    # A contrived stall: out of town, a monster that cannot be reached and
    # never dies, with walking disabled. Nothing to send, no progress.
    world = ColdPlains()
    world.area = offsets.AREA_COLD_PLAINS
    world.position = ARRIVAL
    world.belt = []
    # The NON-patrol run on purpose: with a patrol the bot has somewhere
    # to be and keeps making progress, which is the patrol working rather
    # than the watchdog failing. This test is about the watchdog, so it
    # needs a run that genuinely runs out of things to do.
    run = build_sim(
        world,
        monkeypatch=monkeypatch,
        idle_bail_s=5.0,
        run_file="cold-plains-stage-b.toml",
    )
    # Skip the town/waypoint steps so the stall happens in the field.
    run.engine._index = 2
    world.monsters = [SimMonster(99, (1200, 1200))]  # outside engage radius
    world.armor_ratio = 1.0
    with pytest.raises(IdleBail):
        for _ in range(60):
            run.engine.tick()
            world.advance_tick(0.5)


def test_idle_bail_does_not_fire_while_the_bot_is_working(sim):
    run, world = sim
    assert run_to_completion(run, world)  # no IdleBail escaped


# -- the inventory cleanse (R117) --------------------------------------------------


def test_the_accidental_pickup_was_cleansed(sim):
    run, world = sim
    run_to_completion(run, world)
    assert 700 not in world.inventory  # the junk is gone
    assert world.cleanse_runs  # and it went via the cleanse, not the stash


def test_the_cleanse_waited_for_a_safe_moment(sim):
    # The junk arrives at t10, mid-fight; the cleanse stands still with
    # panels open, so it must not run until nothing is left alive nearby.
    run, world = sim
    run_to_completion(run, world)
    last_death = max(
        i for i, line in enumerate(world.log) if "died of poison" in line
    )
    first_cleanse = min(
        i for i, line in enumerate(world.log) if "cleanse dropped" in line
    )
    assert first_cleanse > last_death


def test_the_cleanse_runs_at_most_a_bounded_number_of_times(sim):
    run, world = sim
    run_to_completion(run, world)
    # Once for the junk, and possibly once more after the retry of the
    # unpickable item re-queues it — never a loop.
    assert 1 <= len(world.cleanse_runs) <= 2
