"""P5's exit test: the whole stack over a scripted Cold Plains.

Everything real except the game — the engine, the ladder with the shipped
`config/necro.toml` numbers, the necro module, the steps, the pickit, the
executor's verified-switch path, and `SafetyMonitor`. The world reacts the
way the client would and, crucially, is allowed to refuse.

The assertions below are the go/no-go artifact in test form; the readable
version is generated by `python -m tests.simworld`.
"""

import pytest

from pd2bot import offsets
from pd2bot.behavior.actions import (
    AttackUnit,
    CastAtPoint,
    CastSelf,
    DrinkPotion,
    PickUpItem,
)
from pd2bot.behavior.engine import IdleBail
from pd2bot.safety import ChickenExit
from tests.simworld import (
    ARRIVAL,
    HEAL_KIND,
    ColdPlains,
    SimMonster,
    build_sim,
    cold_plains_scenario,
)

MAX_TICKS = 400


def run_to_completion(sim, world, *, max_ticks=MAX_TICKS):
    for _ in range(max_ticks):
        if sim.engine.tick():
            return True
        world.advance_tick(0.5)
    return False


@pytest.fixture
def sim(monkeypatch):
    world = cold_plains_scenario()
    return build_sim(world, monkeypatch=monkeypatch), world


# -- the full run ---------------------------------------------------------------


def test_the_whole_run_completes(sim):
    run, world = sim
    assert run_to_completion(run, world), "the run never finished"
    assert run.engine.report.steps_completed == [
        "town_preamble", "waypoint", "clear_radius", "pickup", "done",
    ]
    assert world.preamble_runs == 1
    assert world.travels == [offsets.AREA_COLD_PLAINS]


def test_no_cast_was_ever_sent_on_an_unverified_skill(sim):
    # The single most expensive mistake available to this bot: casting
    # whatever the game happens to have selected. The world counts them.
    run, world = sim
    run_to_completion(run, world)
    assert world.casts_on_unverified_skill == 0


def test_every_cast_was_preceded_by_its_hotkey(sim):
    run, world = sim
    run_to_completion(run, world)
    casts = [e for e in run.trace if isinstance(e.action, CastAtPoint | CastSelf)]
    assert casts, "the run cast nothing at all"
    assert all("verified" in e.detail for e in casts)


def test_attacks_stand_still_and_pickups_do_not(sim):
    run, world = sim
    run_to_completion(run, world)
    modifiers = {}
    for (_, button, stand_still) in run.gated.clicks:
        modifiers.setdefault(button, set()).add(stand_still)
    # Left-clicks come in two flavours and the difference is load-bearing:
    # an attack holds SHIFT, a pickup must not.
    attacks = [e for e in run.trace if isinstance(e.action, AttackUnit)]
    pickups = [e for e in run.trace if isinstance(e.action, PickUpItem)]
    assert attacks and pickups
    assert modifiers["left"] == {True, False}
    assert modifiers["right"] == {False}  # casts are never shifted


def test_the_pack_was_killed_and_the_radius_settled(sim):
    run, world = sim
    run_to_completion(run, world)
    assert world.monsters == []
    assert any("clear for" in line for line in run.engine.report.log)


def test_the_late_straggler_reset_the_settle_timer(sim):
    # A monster arriving mid-settle must not be walked away from.
    run, world = sim
    run_to_completion(run, world)
    assert any("struck 4" in line for line in world.log)


def test_poison_did_the_killing(sim):
    # One strike per monster, not a flurry: a struck monster is dying, and
    # re-stabbing it is time not spent on the next one.
    run, world = sim
    run_to_completion(run, world)
    struck = [e.action.unit_id for e in run.trace if isinstance(e.action, AttackUnit)]
    assert sorted(set(struck)) == [1, 2, 3, 4]
    assert len(struck) == len(set(struck)), f"a monster was re-struck: {struck}"
    assert sum("died of poison" in line for line in world.log) == 4


# -- the ladder ------------------------------------------------------------------


def test_the_damage_spike_triggered_the_escape(sim):
    run, world = sim
    run_to_completion(run, world)
    assert "blood_warp" in run.engine.report.reflex_fires
    assert any("blood warp" in line for line in world.log)


def test_the_escape_fired_exactly_once(sim):
    # Blood warp costs 12% of max hp, which on the next tick reads as more
    # incoming burst damage unless the ladder forgets its history — the bug
    # this sim found, where one escape cost two warps and 240 hp.
    run, world = sim
    run_to_completion(run, world)
    warps = [
        e for e in run.trace
        if isinstance(e.action, CastAtPoint)
        and e.action.skill_id == offsets.SKILL_BLOOD_WARP
    ]
    assert len(warps) == 1


def test_potions_were_drunk_and_armor_kept_up(sim):
    run, world = sim
    run_to_completion(run, world)
    assert any(isinstance(e.action, DrinkPotion) for e in run.trace)
    assert any(isinstance(e.action, CastSelf) for e in run.trace)
    assert world.armor_ratio == pytest.approx(1.0)


def test_the_ladder_outranks_offense(sim):
    # Every tick the ladder fired is a tick the run step did not act on.
    run, world = sim
    run_to_completion(run, world)
    fires = run.engine.report.reflex_fires
    assert fires
    assert len(fires) < run.engine.report.ticks


def test_the_revive_wall_was_raised_to_three(sim):
    run, world = sim
    run_to_completion(run, world)
    assert len(world.revives) == 3
    revive_casts = [
        e for e in run.trace
        if isinstance(e.action, CastAtPoint)
        and e.action.skill_id == offsets.SKILL_REVIVE
    ]
    assert len(revive_casts) == 3  # no wasted casts on already-raised corpses


def test_desecrate_was_bounded(sim):
    # It is cast to MAKE corpses; when it produces none the module must
    # stop rather than spend the run casting.
    run, world = sim
    run_to_completion(run, world)
    desecrates = sum(
        1 for e in run.trace
        if isinstance(e.action, CastAtPoint)
        and e.action.skill_id == offsets.SKILL_DESECRATE
    )
    assert 0 < desecrates <= 12


# -- pickit ----------------------------------------------------------------------


def test_the_pickit_decided_correctly(sim):
    run, world = sim
    run_to_completion(run, world)
    picked = {
        e.action.unit_id: e.action.position
        for e in run.trace if isinstance(e.action, PickUpItem)
    }
    # 501 healing potion -> belt; 503 rare -> keep; 504 unique -> attempted
    # and refused; 502 magic -> never touched, no rule matches it.
    assert 501 in picked and 503 in picked and 504 in picked
    assert 502 not in picked
    assert HEAL_KIND in [kind for kind, _ in world.belt]
    assert 999 in world.inventory


def test_the_stuck_item_was_bounded_and_flagged(sim):
    run, world = sim
    run_to_completion(run, world)
    attempts = [
        e for e in run.trace
        if isinstance(e.action, PickUpItem) and e.action.unit_id == 504
    ]
    # Two bounded rounds, not an endless loop: three attempts before the
    # cleanse, and — because the cleanse freed space — three more after,
    # sharing one memory across both pickup steps.
    assert len(attempts) == 6
    # And the conclusion was recorded where the rest of the game can see it.
    services = run.engine._states[2].services
    assert services.inventory_full
    assert 504 in services.stuck


def test_the_run_still_finished_with_a_full_inventory(sim):
    # A full inventory costs loot; it must not stall the run.
    run, world = sim
    assert run_to_completion(run, world)


# -- the safety layer beneath everything -------------------------------------------


def test_the_monitor_chickens_through_the_engine(monkeypatch):
    world = cold_plains_scenario()
    run = build_sim(world, monkeypatch=monkeypatch)
    # Walk the run into the field, then drop below the 35% threshold.
    for _ in range(10):
        run.engine.tick()
        world.advance_tick(0.5)
    world.hp = 200  # 20% of max
    with pytest.raises(ChickenExit):
        for _ in range(5):
            run.engine.tick()
            world.advance_tick(0.5)


def test_a_stalled_run_idle_bails(monkeypatch):
    # A contrived stall: out of town, a monster that cannot be reached and
    # never dies, with walking disabled. Nothing to send, no progress.
    world = ColdPlains()
    world.area = offsets.AREA_COLD_PLAINS
    world.position = ARRIVAL
    world.belt = []
    run = build_sim(world, monkeypatch=monkeypatch, idle_bail_s=5.0)
    # Skip the town/waypoint steps so the stall happens in the field.
    run.engine._index = 2
    world.monsters = [SimMonster(99, (1200, 1200))]  # outside engage radius
    world.armor_ratio = 1.0
    with pytest.raises(IdleBail):
        for _ in range(60):
            run.engine.tick()
            world.advance_tick(0.5)


def test_idle_bail_does_not_fire_while_the_bot_is_working(sim):
    run, world = sim
    assert run_to_completion(run, world)  # no IdleBail escaped


# -- the inventory cleanse (R117) --------------------------------------------------


def test_the_accidental_pickup_was_cleansed(sim):
    run, world = sim
    run_to_completion(run, world)
    assert 700 not in world.inventory  # the junk is gone
    assert world.cleanse_runs  # and it went via the cleanse, not the stash


def test_the_cleanse_waited_for_a_safe_moment(sim):
    # The junk arrives at t10, mid-fight; the cleanse stands still with
    # panels open, so it must not run until nothing is left alive nearby.
    run, world = sim
    run_to_completion(run, world)
    last_death = max(
        i for i, line in enumerate(world.log) if "died of poison" in line
    )
    first_cleanse = min(
        i for i, line in enumerate(world.log) if "cleanse dropped" in line
    )
    assert first_cleanse > last_death


def test_the_cleanse_runs_at_most_a_bounded_number_of_times(sim):
    run, world = sim
    run_to_completion(run, world)
    # Once for the junk, and possibly once more after the retry of the
    # unpickable item re-queues it — never a loop.
    assert 1 <= len(world.cleanse_runs) <= 2
